Merge branch 'dev' of https://github.com/jumpserver/jumpserver into ticket_direct_approval
jumpserver/jumpserver pull request #12662
Opened 2024-02-19 03:25 UTC by fit2bot

2024-02-19 03:28 UTC, O-Jiangweidong approved these changes

2024-02-20 06:42 UTC, BaiJiangJie commented on apps/tickets/views/approve.py
> +        return user
这样获取 user 应该有风险。

2024-02-20 06:43 UTC, BaiJiangJie requested changes
考虑一下获取 user 的问题。

2024-02-21 03:38 UTC, BaiJiangJie commented on apps/tickets/views/approve.py
> +        return user
跟 token 有关系，token 不泄漏不会有问题。

2024-02-21 03:38 UTC, BaiJiangJie approved these changes

2024-02-21 03:39 UTC, merged