fix: 远程应用列表接口报错
jumpserver/jumpserver pull request #12699
Opened 2024-02-23 08:46 UTC by fit2bot

fix: 远程应用列表接口报错

2024-02-23 08:46 UTC, w940853815 approved these changes

2024-02-26 09:10 UTC, BaiJiangJie commented on apps/terminal/api/applet/applet.py
> +            with open(os.path.join(obj.path, 'manifest.yml'), encoding='utf8') as f:
path = os.path.join(obj.path, 'manifest.yml')

复用。

2024-02-26 09:10 UTC, BaiJiangJie requested changes
复用逻辑。

2024-02-26 11:01 UTC, BaiJiangJie commented on apps/terminal/api/applet/applet.py
>          return manifest
```
    @staticmethod
    def read_manifest_with_i18n(obj, lang='zh'):
        with open(os.path.join(obj.path, 'manifest.yml'), encoding='utf8') as f:
            manifest = yaml_load_with_i18n(f, lang)
        path = os.path.join(obj.path, 'manifest.yml')
        if not os.path.exists(path):
            return {}
        with open(path, encoding='utf8') as f:
            manifest = yaml_load_with_i18n(f, lang)
            return manifest
```

2024-02-26 11:02 UTC, BaiJiangJie approved these changes

2024-02-26 11:03 UTC, merged