perf: 优化三方登录创建的用户邮箱会校验，非法邮箱会重置成默认格式
jumpserver/jumpserver pull request #12775
Opened 2024-03-07 08:40 UTC by fit2bot

perf: 优化三方登录创建的用户邮箱会校验，非法邮箱会重置成默认格式

2024-03-07 08:42 UTC, O-Jiangweidong commented
有的客户邮箱是包含变量格式的@{AL_NULL}，只能创建一个用户，其他用户登录会导致邮箱已经存在而无法登陆

2024-03-07 08:49 UTC, O-Jiangweidong approved these changes

2024-03-08 10:03 UTC, BaiJiangJie commented on apps/users/utils.py
> +            email = f'{username}@{email_suffix}'
优化一下代码，validate_email 支持接受一个字符串列表，按顺序匹配，第一个成功的返回，不成功返回默认值。

email = valid_email(emails=[], default='')
return email

2024-03-08 10:03 UTC, BaiJiangJie requested changes
优化一下。

2024-03-11 10:41 UTC, BaiJiangJie approved these changes

2024-03-11 10:41 UTC, merged