perf: 支持终断批量快捷命令执行的任务
jumpserver/jumpserver pull request #12805
Opened 2024-03-13 10:20 UTC by fit2bot

perf: 支持终断批量快捷命令执行的任务

2024-03-13 10:21 UTC, w940853815 approved these changes

2024-03-14 03:30 UTC, BaiJiangJie commented on apps/ops/signal_handlers.py
> +                if child.name() == 'ssh' and child.pid != 1:
`
if child.pid == 1:
    continue
if child.name() != 'ssh':
    continue

child.kill()
logger.debug()
`

2024-03-14 03:31 UTC, BaiJiangJie commented on apps/ops/signal_handlers.py
> +                if child.name() == 'ssh' and child.pid != 1:
日志描述文案，规范一下。

2024-03-14 03:33 UTC, BaiJiangJie requested changes
Need change!

2024-03-14 06:20 UTC, BaiJiangJie approved these changes

2024-03-14 06:20 UTC, merged