feat: 支持开启、关闭定时任务执行
jumpserver/jumpserver pull request #12845
Opened 2024-03-20 10:16 UTC by fit2bot

feat: 支持开启、关闭定时任务执行

2024-03-20 10:24 UTC, w940853815 approved these changes

2024-03-21 06:25 UTC, BaiJiangJie commented on apps/ops/api/celery.py
> +        queryset = self.process_queryset(queryset)
跟之前的逻辑一样，分别在不同的逻辑中调用。

2024-03-21 06:26 UTC, BaiJiangJie commented on apps/ops/api/celery.py
> +    lookup_value_regex = '[\w.@]+'
这两个是做什么的？

2024-03-21 06:27 UTC, BaiJiangJie commented on apps/ops/api/celery.py
> +        crontab_tasks = []
periodic_tasks = crontab + interval

2024-03-21 06:29 UTC, BaiJiangJie requested changes
Need change！

2024-03-21 10:23 UTC, BaiJiangJie approved these changes

2024-03-21 10:23 UTC, merged