perf: 社区版去掉一些东西
jumpserver/jumpserver pull request #13131
Opened 2024-04-25 08:13 UTC by fit2bot

perf: 社区版去掉一些东西

2024-04-25 08:14 UTC, w940853815 approved these changes

2024-04-26 03:10 UTC, BaiJiangJie commented on apps/users/serializers/user.py
> +
增加 fields_xpack=[] 字段

2024-04-26 03:11 UTC, BaiJiangJie commented on apps/users/serializers/user.py
> +
<img width="665" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/81f5de31-cabc-4f8c-9ee5-0901ba6ac228">

XPACKModelFieldsMixin

2024-04-26 03:12 UTC, BaiJiangJie requested changes
need changes!

2024-04-26 06:22 UTC, BaiJiangJie commented on apps/common/serializers/mixin.py
> +        return fields_xpack
return set()

2024-04-26 06:22 UTC, BaiJiangJie commented on apps/users/serializers/user.py
> +                        "feishu_id", "lark_id", "slack_id"]
换行

2024-04-28 06:12 UTC, BaiJiangJie commented on apps/common/serializers/mixin.py
> +        return fields_xpack
最后 set() 一下

2024-04-28 07:58 UTC, BaiJiangJie approved these changes

2024-04-28 07:58 UTC, merged