perf: Modify error message for desktop client login
jumpserver/jumpserver pull request #13763
Opened 2024-07-18 09:19 UTC by fit2bot

perf: Modify error message for desktop client login

2024-07-18 11:45 UTC, BaiJiangJie commented on apps/i18n/core/zh/LC_MESSAGES/django.po
> +msgstr "很抱歉，不支持客户端跳转登录，请重新登录"
不要抱歉

2024-07-18 11:46 UTC, BaiJiangJie commented on apps/authentication/views/dingtalk.py
> -        msg = _("The system configuration is incorrect. Please contact your administrator")
这几个 `get_verify_state_failed_response` 方法，看看能不能抽象出去。

2024-07-18 11:46 UTC, BaiJiangJie commented on apps/authentication/views/base.py
> +            return response
不是 1062 的报错，也是一样的提示吗？

2024-07-18 11:47 UTC, BaiJiangJie requested changes
Need changes.

2024-07-19 02:12 UTC, BaiJiangJie commented on apps/authentication/views/base.py
> +            return response
pgsql 没有 1062

2024-07-19 02:23 UTC, BaiJiangJie commented on apps/i18n/core/zh/LC_MESSAGES/django.po
> +msgstr "不支持客户端跳转登录，请重新登录"
为了您的安全，客户端不支持自动跳转登录。如果需要在客户端中打开，请重新登录。

2024-07-19 03:03 UTC, BaiJiangJie commented on apps/authentication/views/mixins.py
> +        return self.request.GET.get('state') == self.request.session.get(session_key)
代码风格

2024-07-19 03:04 UTC, BaiJiangJie commented on apps/authentication/views/wecom.py
> +        return self.request.session.get(WECOM_STATE_SESSION_KEY)
这个地方。

2024-07-19 03:34 UTC, w940853815 approved these changes

2024-07-19 05:44 UTC, w940853815 approved these changes

2024-07-23 06:04 UTC, w940853815 approved these changes

2024-07-24 02:30 UTC, BaiJiangJie commented on apps/authentication/views/wecom.py
> +        return self.request.session.get(WECOM_STATE_SESSION_KEY)
`return self.verify_state_with_session_key(WECOM_STATE_SESSION_KEY)`

2024-07-24 02:43 UTC, w940853815 approved these changes

2024-07-24 02:59 UTC, BaiJiangJie approved these changes

2024-07-24 02:59 UTC, merged