feat: support configuring multiple SSH keys for users
jumpserver/jumpserver pull request #13824
Opened 2024-07-29 11:38 UTC by fit2bot

feat: support configuring multiple SSH keys for users

2024-07-30 08:48 UTC, BaiJiangJie commented on apps/authentication/models/ssh_key.py
> +                             db_constraint=False, related_name='ssh_keys')
换行风格。

2024-07-30 08:49 UTC, BaiJiangJie commented on apps/authentication/serializers/ssh_key.py
> +            'id', 'user', 'public_key_comment', 'public_key_hash_md5', 'date_last_used', 'date_created', 'date_updated'
代码风格。

超过 100 了吗？

2024-07-30 08:50 UTC, BaiJiangJie requested changes
代码风格。

2024-07-31 03:07 UTC, w940853815 approved these changes

2024-08-05 06:39 UTC, BaiJiangJie commented on apps/users/urls/api_urls.py
> -    path('profile/public-key/', api.UserPublicKeyApi.as_view(), name='user-public-key'),
API 是否考虑兼容一下。

2024-08-05 06:45 UTC, BaiJiangJie commented on apps/users/urls/api_urls.py
> -    path('profile/public-key/', api.UserPublicKeyApi.as_view(), name='user-public-key'),
先不兼容了。

2024-08-05 07:22 UTC, BaiJiangJie approved these changes

2024-08-05 07:22 UTC, merged