fix: 500 error caused by duplicate email or username
jumpserver/jumpserver pull request #14066
Opened 2024-08-30 09:59 UTC by fit2bot

fix: 500 error caused by duplicate email or username

2024-08-30 09:59 UTC, w940853815 commented
![image](https://github.com/user-attachments/assets/19a5e1a2-6ddf-409f-b9ae-00710c4d39c4)

2024-08-30 10:00 UTC, w940853815 approved these changes

2024-09-02 02:47 UTC, ibuler approved these changes

2024-09-02 02:48 UTC, ibuler commented
Title and msg could be absolute same

2024-09-02 03:24 UTC, w940853815 commented
![image](https://github.com/user-attachments/assets/4eeefd1f-c619-4bd5-b26a-77f6759cf85e)

2024-09-05 11:31 UTC, BaiJiangJie commented on apps/i18n/core/zh_Hant/LC_MESSAGES/django.po
> +"錄。這種定期清理過程有助於釋放儲存空間並提高資料管理的安全性和整體效能。"
这个是不是多了其他的文案描述？

2024-09-05 11:31 UTC, BaiJiangJie requested changes
1

2024-09-06 01:37 UTC, w940853815 commented on apps/i18n/core/zh_Hant/LC_MESSAGES/django.po
> +"錄。這種定期清理過程有助於釋放儲存空間並提高資料管理的安全性和整體效能。"
没有 只是换行

2024-09-06 02:00 UTC, BaiJiangJie approved these changes

2024-09-06 02:09 UTC, BaiJiangJie approved these changes

2024-09-06 02:22 UTC, merged