feat: 工单支持审批时选择资产
jumpserver/jumpserver pull request #8187
Opened 2022-05-04 13:20 UTC by fit2bot

feat: 工单支持审批时选择资产

2022-05-05 03:46 UTC, ibuler commented
太复杂，不愿意 review 了

2022-05-07 06:23 UTC, BaiJiangJie commented on apps/tickets/serializers/ticket/ticket.py
> +
这里用 serializers.ReadOnlyField(source='current_meta') 可以吗？

2022-05-07 06:27 UTC, BaiJiangJie commented on apps/tickets/serializers/ticket/meta/ticket_type/common.py
> +    return False
这里函数名调整一下，和里面的 step 关联起来会不会更好一些？

2022-05-07 06:30 UTC, BaiJiangJie commented on apps/tickets/serializers/ticket/meta/ticket_type/apply_asset.py
> +        label=_('Apply assets display'), default=list,
这里实参 allow_null=True 如果去掉，meta字段里如果缺少当前字段可能直接就 500 了。

2022-05-07 06:30 UTC, BaiJiangJie commented on apps/tickets/serializers/ticket/meta/ticket_type/apply_asset.py
> -        default=list,
同上。

2022-05-07 06:40 UTC, BaiJiangJie commented on apps/tickets/migrations/0016_migrate_approve_info.py
> +    model.objects.bulk_update(tickets, fields=('process_map',))
这里修改完 process 值后显示的给 ticket 赋值一下会不会更好？

2022-05-07 06:41 UTC, feng626 commented on apps/tickets/serializers/ticket/meta/ticket_type/apply_asset.py
> +        label=_('Apply assets display'), default=list,
read_only=True 是只读的

2022-05-07 06:45 UTC, BaiJiangJie commented on apps/tickets/handler/apply_asset.py
> -
删掉了？

2022-05-07 06:49 UTC, BaiJiangJie commented on apps/tickets/api/ticket.py
> +        return response
提前获取 response 的值，后更新 instance 的字段，最后返回的 data 是最新的数据吗？

2022-05-07 06:55 UTC, BaiJiangJie requested changes
整体 review 了一下，看着没有太大问题。
只是 meta、process_meta 等一些字段因为没有结构化，所以掌控感不是很强。

2022-05-07 07:02 UTC, BaiJiangJie commented on apps/tickets/serializers/ticket/meta/ticket_type/apply_asset.py
> +        label=_('Apply assets display'), default=list,
不是read_only，是 allow_null。
allow_null 有一个作用是反序列化的时候如果数据库里丢失了这个字段，也会抛出异常。

2022-05-07 09:10 UTC, BaiJiangJie commented on apps/tickets/const.py
> +    closed = 'closed', _('Closed')
没有看到对应的迁移文件。

2022-05-09 03:34 UTC, BaiJiangJie commented on apps/tickets/api/ticket.py
> +        return response
能看到吗？

2022-05-09 04:20 UTC, BaiJiangJie commented
process_map 里的字段没有进行结构化定义，
目前包括一部分 apply_ ，一部分 approve_，其实应该显示结构化定义为 approve_ 的哪些字段。
所以，暂时不考虑合并。

2022-05-31 06:19 UTC, closed without merging