feat: 支持 piico 设备国密加密
jumpserver/jumpserver pull request #8800
Opened 2022-08-23 09:41 UTC by fit2bot

feat: 支持 piico 设备国密加密

2022-08-23 10:18 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/__init__.py
> +    return d
需要 try 一下吗？

2022-08-23 10:20 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/session.py
> +        pass
pass？还是遗漏？

2022-08-23 10:20 UTC, Aaron3S commented on apps/common/sdk/gm/piico/device.py
> +    def open(self, driver_path="./libpiico_ccmu"):
此处默认驱动路径，缺少驱动文件后缀名
./libpiico_ccmu => ./libpiico_ccmu.so

2022-08-23 10:21 UTC, ibuler commented
/lgtm

2022-08-23 10:21 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/session.py
> +        if not ret == 0:
ret != 0

2022-08-23 10:21 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/session.py
> +        if not ret == 0:
ret != 0

2022-08-23 10:22 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/session.py
> +        if not ret == 0:
ret != 0

2022-08-23 10:22 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/session_mixin.py
> +        if not ret == 0:
ret != 0

2022-08-23 10:22 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/session_mixin.py
> +            raise PiicoError("hash init failed,alg id is {}".format(alg_id), ret)
ret != 0

2022-08-23 10:22 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/session_mixin.py
> +        if not ret == 0:
ret != 0

2022-08-23 10:22 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/session_mixin.py
> +        if not ret == 0:
ret != 0

2022-08-23 10:22 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/session_mixin.py
> +        if not ret == 0:
ret != 0

2022-08-23 10:23 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/session_mixin.py
> +        if not ret == 0:
ret != 0

2022-08-23 10:23 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/session_mixin.py
> +            if not ret == 0:
ret != 0

2022-08-23 10:23 UTC, BaiJiangJie commented on apps/common/sdk/gm/piico/session_mixin.py
> +            if not ret == 0:
ret != 0

2022-08-23 10:23 UTC, BaiJiangJie requested changes
Please change

2022-08-24 06:54 UTC, ibuler commented on apps/common/utils/crypto.py
> +                    piico_driver_path = settings.PIICO_DRIVER_PATH if settings.PIICO_DRIVER_PATH \
判断 path 是否 exist

2022-08-24 06:57 UTC, ibuler approved these changes
/lgtm

2022-08-24 06:57 UTC, ibuler approved these changes

2022-08-24 06:58 UTC, merged